version: '3'
services:

  nginx-proxy:
    image: jwilder/nginx-proxy
    restart: always
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./volumes/nginx/conf.d:/etc/nginx/conf.d
    - ./volumes/nginx/html:/usr/share/nginx/html
    - ./volumes/nginx/htpasswd:/etc/nginx/htpasswd
    - ./volumes/nginx/dhparam:/etc/nginx/dhparam
    - ./volumes/nginx/vhost:/etc/nginx/vhost.d
    - ./volumes/nginx/certs:/etc/nginx/certs:ro
    - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
    - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    depends_on:
    - "nginx-proxy"
    volumes:
    - ./volumes/nginx/conf.d:/etc/nginx/conf.d
    - ./volumes/nginx/vhost:/etc/nginx/vhost.d
    - ./volumes/nginx/html:/usr/share/nginx/html
    - ./volumes/nginx/certs:/etc/nginx/certs:rw
    - /var/run/docker.sock:/var/run/docker.sock:ro

  streama:
    image: anapsix/alpine-java:8
    volumes:
    - ./streama.jar:/app/app.jar
    - ./application.yml:/app/application.yml
    - ./volumes/streama/uploads:/app/uploads
    - ./volumes/streama/local-files:/app/local-files
    working_dir: /app
    command: java -jar app.jar
    ports:
    - "127.0.0.1:8080:8080"
    depends_on:
    - db
    environment:
    - VIRTUAL_HOST=streama.your-host.net
    - VIRTUAL_PORT=8080
    - LETSENCRYPT_HOST=streama.your-host.net
    - LETSENCRYPT_EMAIL=you@gmail.com

  db:
    image: mariadb:10
    volumes:
    - ./volumes/db:/var/lib/mysql
    restart: always
    command: --max_allowed_packet=256M --innodb_log_buffer_size=32M --innodb_buffer_pool_size=128M
    environment:
    - MYSQL_ROOT_PASSWORD=INSERT_SEC_PASSWORD
    - MYSQL_DATABASE=streama
    - MYSQL_USER=streama
    - MYSQL_PASSWORD=INSERT_ANOTHER_SEC_PASSWORD
    ports:
      - 127.0.0.1:3306:3306

  mail:
    image: bytemark/smtp
    restart: always
